### ISSUE TITLE
Error 500 ipn.php

### ISSUE THREAD

**Issue by MEANcisco** [harregoces/moodle-enrol_mercadopago#3]
Hola! 
Maravilloso proyecto, pero sabes que cuando hago la integración, me pasa los pagos y todo, pero al momento de llevarme a ipn.php este me arroja un error 500 y no entiendo por qué, si necesitas mas información estoy atento y te comento.

muchas gracias <3

**Comment by AndresJ551** [comment]
Lo mismo que MEANcisco, error 500 al completar el pago e intentar generar la matrícula.

El error es ; inesperado, falta ) en línea 55 de ipn.php

/// Keep out casual intruders
if (empty($_POST) or !empty($_GET)) {
    http_response_code(400);
    throw new moodle_exception('invalidrequest', 'core_error');
}

Creo que es relacionado a la versión de PHP que corre Docker Moodle.

Saludos.

**Comment by MEANcisco** [comment]
Buenas!
El archivo de ipn.php fue modificado, sin embargo continua dando error 500 por algún motivo existe alguna forma de saber que sucede? ya que no entrega ningún return, o si existe algún log para estas situaciones me gustaría mucho saber donde se guarda esa información para poder compartirla

**Comment by AndresJ551** [comment]
Hola @MEANcisco, si tu servidor no tiene habilitado el log es difícil de saber.
En mi caso pude ver que esa línea tenía el paréntesis faltante, después la 47 tiene otro error de validación y tiene que reemplazarse:
if (empty($_POST) && empty($_GET)) {

Esa solo te devuelve 400 no 500 como comentas. Si hay otro error de sintaxis no lo recuerdo.

Saludos.
